version: '3.4'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1432:1433"

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=
     
    restart: always

  ecommerce_api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    build:
      context: .
      dockerfile: Ecommerce_Api/Dockerfile
    depends_on:
    - "mssql"




